### ISSUE TITLE
创建项目失败

### ISSUE THREAD

**Issue by july-12** [lyfeyaj/ewa#1]
### ewa new xxx 报错

[09:31:04] [ewa] 初始化 ewa 项目: wx-ewa
/Users/yubtan/.config/yarn/global/node_modules/yargs/yargs.js:1133
      else throw err
           ^

Error: /Users/yubtan/test/wx-ewa/package.json: ENOENT: no such file or directory, open '/Users/yubtan/test/wx-ewa/package.json'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.readFileSync (/Users/yubtan/.config/yarn/global/node_modules/jsonfile/index.js:61:22)
    at install (/Users/yubtan/.config/yarn/global/node_modules/ewa-cli/lib/commands/install.js:24:26)
    at create (/Users/yubtan/.config/yarn/global/node_modules/ewa-cli/lib/commands/create.js:36:3)
    at Object.require.usage.command [as handler] (/Users/yubtan/.config/yarn/global/node_modules/ewa-cli/lib/cli.js:13:33)
    at Object.runCommand (/Users/yubtan/.config/yarn/global/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/yubtan/.config/yarn/global/node_modules/yargs/yargs.js:1046:30)
    at Object.get [as argv] (/Users/yubtan/.config/yarn/global/node_modules/yargs/yargs.js:989:21)
    at Object.<anonymous> (/Users/yubtan/.config/yarn/global/node_modules/ewa-cli/lib/cli.js:37:3)

**Comment by lyfeyaj** [comment]
使用的是最新版么 `v0.1.28`？

**Comment by july-12** [comment]
@lyfeyaj  我用yarn装的ewa，是版本过低了，我在重新装一下试试

![image](https://user-images.githubusercontent.com/920487/42857769-ebfbd1ea-8a7d-11e8-9f76-c1f5257d2d72.png)

**Comment by lyfeyaj** [comment]
安装新版后还有问题么？

**Comment by july-12** [comment]
@lyfeyaj 更新ewa-cli之后，ok了，已经正常启动
![image](https://user-images.githubusercontent.com/920487/42862300-82ffed66-8a91-11e8-8a8b-6212ca182285.png)
