### ISSUE TITLE
请问如何在ewa项目下使用 towxml ？

### ISSUE THREAD

**Issue by oimken** [lyfeyaj/ewa#23]
一直使用ewa，真的很好用，谢谢作者一直坚持更新！
现在碰到个问题，想使用这个来转换markdown，

https://github.com/sbfkcel/towxml

但它的引入方式有点另类，在src内按它的安装步骤来做，编译的时候就会出错,

希望您能抽空看看怎么才能正常使用这类插件, 非常感谢！

错误如下：

```
84 problems (21 errors, 63 warnings)

 @ /Volumes/Works/Sites/mini/src/towxml/parse/markdown/index.js 42:9-30
 @ /Volumes/Works/Sites/mini/src/towxml/index.js

ERROR in /Volumes/Works/Sites/mini/src/towxml/config.js
Module build failed (from /usr/local/lib/node_modules/ewa-cli/node_modules/eslint-loader/index.js):
Error: ENOENT: no such file or directory, open '/Volumes/Works/Sites/mini/src/utils/towxml/config.js'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1281:35)
    at /usr/local/lib/node_modules/ewa-cli/node_modules/eslint/lib/cli-engine.js:545:16
    at Array.forEach (<anonymous>)
    at Function.outputFixes (/usr/local/lib/node_modules/ewa-cli/node_modules/eslint/lib/cli-engine.js:544:97)
    at printLinterOutput (/usr/local/lib/node_modules/ewa-cli/node_modules/eslint-loader/index.js:81:24)
    at /usr/local/lib/node_modules/ewa-cli/node_modules/eslint-loader/index.js:261:11
    at /usr/local/lib/node_modules/ewa-cli/node_modules/loader-fs-cache/index.js:122:24
    at Gunzip.cb (/usr/local/lib/node_modules/ewa-cli/node_modules/loader-fs-cache/index.js:47:14)
    at Gunzip.zlibBufferOnEnd (zlib.js:139:10)
    at Gunzip.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1199:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

ERROR in /Volumes/Works/Sites/mini/src/app.js
Module not found: Error: Can't resolve 'towxml/index' in '/Volumes/Works/Sites/mini/src'
resolve 'towxml/index' in '/Volumes/Works/Sites/mini/src'
  Parsed request is a module
  using description file: /Volumes/Works/Sites/mini/package.json (relative path: ./src)
    resolve as module
      /Volumes/Works/Sites/mini/src/node_modules doesn't exist or is not a directory
      /Volumes/Resources/Sites/node_modules doesn't exist or is not a directory
      /Volumes/Resources/node_modules doesn't exist or is not a directory
      /Volumes/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Volumes/Works/Sites/mini/node_modules
        using description file: /Volumes/Works/Sites/mini/package.json (relative path: ./node_modules)
          using description file: /Volumes/Works/Sites/mini/package.json (relative path: ./node_modules/towxml/index)
            no extension
              /Volumes/Works/Sites/mini/node_modules/towxml/index doesn't exist
            .ts
              /Volumes/Works/Sites/mini/node_modules/towxml/index.ts doesn't exist
            .js
              /Volumes/Works/Sites/mini/node_modules/towxml/index.js doesn't exist
            .html
              /Volumes/Works/Sites/mini/node_modules/towxml/index.html doesn't exist
            .wxml
              /Volumes/Works/Sites/mini/node_modules/towxml/index.wxml doesn't exist
            .wxs
              /Volumes/Works/Sites/mini/node_modules/towxml/index.wxs doesn't exist
            .css
              /Volumes/Works/Sites/mini/node_modules/towxml/index.css doesn't exist
            .wxss
              /Volumes/Works/Sites/mini/node_modules/towxml/index.wxss doesn't exist
            .scss
              /Volumes/Works/Sites/mini/node_modules/towxml/index.scss doesn't exist
            .sass
              /Volumes/Works/Sites/mini/node_modules/towxml/index.sass doesn't exist
            as directory
              /Volumes/Works/Sites/mini/node_modules/towxml/index doesn't exist
      looking for modules in /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules
        using description file: /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/package.json (relative path: ./node_modules)
          using description file: /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/package.json (relative path: ./node_modules/towxml/index)
            no extension
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index doesn't exist
            .ts
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.ts doesn't exist
            .js
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.js doesn't exist
            .html
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.html doesn't exist
            .wxml
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.wxml doesn't exist
            .wxs
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.wxs doesn't exist
            .css
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.css doesn't exist
            .wxss
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.wxss doesn't exist
            .scss
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.scss doesn't exist
            .sass
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.sass doesn't exist
            as directory
              /usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index doesn't exist
      looking for modules in /usr/local/lib/node_modules/ewa-cli/node_modules
        using description file: /usr/local/lib/node_modules/ewa-cli/package.json (relative path: ./node_modules)
          using description file: /usr/local/lib/node_modules/ewa-cli/package.json (relative path: ./node_modules/towxml/index)
            no extension
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index doesn't exist
            .ts
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.ts doesn't exist
            .js
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.js doesn't exist
            .html
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.html doesn't exist
            .wxml
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxml doesn't exist
            .wxs
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxs doesn't exist
            .css
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.css doesn't exist
            .wxss
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxss doesn't exist
            .scss
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.scss doesn't exist
            .sass
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.sass doesn't exist
            as directory
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index doesn't exist
      looking for modules in /usr/local/lib/node_modules/ewa-cli/node_modules
        using description file: /usr/local/lib/node_modules/ewa-cli/package.json (relative path: ./node_modules)
          using description file: /usr/local/lib/node_modules/ewa-cli/package.json (relative path: ./node_modules/towxml/index)
            no extension
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index doesn't exist
            .ts
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.ts doesn't exist
            .js
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.js doesn't exist
            .html
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.html doesn't exist
            .wxml
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxml doesn't exist
            .wxs
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxs doesn't exist
            .css
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.css doesn't exist
            .wxss
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxss doesn't exist
            .scss
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.scss doesn't exist
            .sass
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.sass doesn't exist
            as directory
              /usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index doesn't exist
[/Volumes/Works/Sites/mini/src/node_modules]
[/Volumes/Resources/Sites/node_modules]
[/Volumes/Resources/node_modules]
[/Volumes/node_modules]
[/node_modules]
[/Volumes/Works/Sites/mini/node_modules/towxml/index]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.ts]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.js]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.html]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.wxml]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.wxs]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.css]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.wxss]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.scss]
[/Volumes/Works/Sites/mini/node_modules/towxml/index.sass]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.ts]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.js]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.html]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.wxml]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.wxs]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.css]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.wxss]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.scss]
[/usr/local/lib/node_modules/ewa-cli/node_modules/ewa-webpack/node_modules/towxml/index.sass]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.ts]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.js]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.html]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxml]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxs]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.css]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.wxss]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.scss]
[/usr/local/lib/node_modules/ewa-cli/node_modules/towxml/index.sass]
 @ /Volumes/Works/Sites/mini/src/app.js 28:10-33
```

**Comment by lyfeyaj** [comment]
##### 尝试按照下面的方式使用：

1、升级 ewa-cli 到最新的版本
2、准备工作，安装必要工具（git/npm等）
3、新建空目录（用于构建towxml），命令行输入 git clone https://github.com/sbfkcel/towxml.git
4、上一步执行完毕后，在目录下会增加一个towxml目录，cd towxml ，输入 npm install
5、上一步结束后，根据需要修改配置文件，（详见wiki文档）或直接进入下一步
6、输入 npm run build 构建towxml，结束后会在桌面上生成构建好的 towxml
7、拷贝 towxml 到项目的 src 目录下面
8、按照 towxml 项目的文档使用方法使用

**Comment by lyfeyaj** [comment]
我使用最新的 ewa-cli 试了下，是可以正常编译的

**Comment by oimken** [comment]
已经升级了最新版本了，但是还是，一编译就出错：
```
ERROR in /Users/Ken/Sites/mini/src/towxml/audio-player/Audio.js
Module build failed (from /usr/local/lib/node_modules/ewa-cli/node_modules/eslint-loader/index.js):
Error: ENOENT: no such file or directory, open '/Volumes/Resources/Sites/mini/src/towxml/audio-player/Audio.js'

.....
```

**Comment by oimken** [comment]
一直没成功，刚才又试了一下，貌似路径问题，

**Comment by oimken** [comment]
清理 dist之后可以编译了，谢谢你的帮助！
