### ISSUE TITLE
ewa init 报错

### ISSUE THREAD

**Issue by huangyuzai** [lyfeyaj/ewa#49]
$ ewa init
[23:53:55] [ewa] 正在初始化 ewa 项目...
[23:53:55] [ewa] 创建临时文件夹 F:\hyuzai\_wx\__tmp_src__
[23:53:55] [ewa] 准备移动文件或文件夹...
[23:53:55] [ewa] 正在移动 __tmp_src__ 至 __tmp_src__\__tmp_src__
C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\node_modules\yargs\build\index.cjs:2772
                throw err;
                ^

Error: Cannot move 'F:/hyuzai/_wx/__tmp_src__' to a subdirectory of itself, 'F:\hyuzai\_wx\__tmp_src__\__tmp_src__'.
    at Object.checkPathsSync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\node_modules\fs-extra\lib\util\stat.js:54:11)
    at Object.moveSync (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\node_modules\fs-extra\lib\move-sync\move-sync.js:14:28)
    at sourceFiles.map.source (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\lib\commands\init.js:51:8)
    at Array.map (<anonymous>)
    at init (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\lib\commands\init.js:41:15)
    at Object.require.locale.usage.command.command [as handler] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\lib\cli.js:29:31)
    at Object.runCommand (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\node_modules\yargs\build\index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\node_modules\yargs\build\index.cjs:2697:57)
    at Object.get [as argv] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\node_modules\yargs\build\index.cjs:2651:25)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\ewa-cli\lib\cli.js:97:3)

想问一下大佬这是啥问题，是在原有的原生微信小程序上面进行初始化，大佬救救我！

**Comment by lyfeyaj** [comment]
看上去是 init 命令在 windows 环境下有兼容性问题，你可以尝试使用 ewa 新建一个项目，如 `ewa new my_project` 然后手动把你的源代码全部拷贝到 `my_project/src` 里面去，然后就可以正常使用了

**Comment by huangyuzai** [comment]
好的！我试一下

**Comment by lyfeyaj** [comment]
版本你 `ewa-cli@1.2.1`  中已修复
