### ISSUE TITLE
可以给命令的路径加上双引号吗

### ISSUE THREAD

**Issue by ltxhhz** [lyfeyaj/ewa#51]
我还没入门就要被劝退了
```
C:\Users\12708\WeChatProjects\em-Copy>npm start

> em-Copy@1.0.0 start C:\Users\12708\WeChatProjects\em-Copy
> ewa clean && ewa start

[22:04:34] [ewa] 正在清理 dist 目录... 
[22:04:34] [ewa] 清理完成 !
[22:04:35] [ewa] 正在启动项目实时编译...
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'D:\Program'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
(node:7856) UnhandledPromiseRejectionWarning: Error: Command failed: cd C:\Users\12708\WeChatProjects\em-Copy && node D:\Program Files\nodejs\node_global\node_modules\ewa-cli\node_modules\ewa-webpack\lib\run.js
```

**Comment by lyfeyaj** [comment]
`ewa-cli@v1.2.4` 中已修复
