### ISSUE TITLE
原生微信小程序初始化报错

### ISSUE THREAD

**Issue by ltxhhz** [lyfeyaj/ewa#52]
昨天提的issue是命令中路径的问题，我把npm包的路径修改了，解决了
现在初始化原生小程序又有问题，直接init和创建再移动代码的方法都试过了，都这样
我原生的微信小程序已经上线了，所以应该是没问题的，但这里初始化的时候报一大堆错，而且编译完的app.wxss文件里面是js代码

![image](https://user-images.githubusercontent.com/51697596/124378181-af7f3080-dce2-11eb-8ac7-7297e0eb8f83.png)
![image](https://user-images.githubusercontent.com/51697596/124378185-b6a63e80-dce2-11eb-8751-428dc8d90670.png)

```
C:\Users\12708\WeChatProjects\em-Copy>npm start

> em-Copy@1.0.0 start
> ewa clean && ewa start

[16:09:11] [ewa] 正在清理 dist 目录...
[16:09:11] [ewa] 清理完成 !
[16:09:11] [ewa] 正在启动项目实时编译...
[16:09:12] [ewa] [nodemon] 2.0.9
[16:09:12] [ewa] [nodemon] to restart at any time, enter `rs`
[16:09:12] [ewa] [nodemon] watching path(s): .ewa\**\*
[16:09:12] [ewa] [nodemon] watching extensions: js
[16:09:12] [ewa] [nodemon] starting `node D:\node_global\node_modules\ewa-cli\node_modules\webpack-cli\bin\cli.js --config D:\node_global\node_modules\ewa-cli\node_modules\ewa-webpack\lib\config.js --watch`
[16:09:14] [ewa] 构建类型: 微信小程序
[16:09:14] [ewa] 构建目录: C:\Users\12708\WeChatProjects\em-Copy\dist

webpack is watching the files…


× Webpack
  Compiled with some errors in 4.02s

[16:09:18] [ewa]
[16:09:18] [ewa] AutoCleanUnusedFilesPlugin skipped due to errors.
Time: 4025ms
Built at: 2021/07/04 下午4:09:18
   72 modules

WARNING in
C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\app.js
  33:9  warning  Unexpected console statement  no-console
  45:7  warning  Unexpected console statement  no-console

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\colorui\components\cu-custom\cu-custom.js
  51:10  warning  Unexpected console statement  no-console

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\components\color-picker\color-picker.js
  371:15  warning  'greenRatioX' is assigned a value but never used  no-unused-vars
  372:15  warning  'blueRatioX' is assigned a value but never used   no-unused-vars
  377:15  warning  'redRatioX' is assigned a value but never used    no-unused-vars
  378:15  warning  'blueRatioX' is assigned a value but never used   no-unused-vars
  383:15  warning  'redRatioX' is assigned a value but never used    no-unused-vars
  384:15  warning  'greenRatioX' is assigned a value but never used  no-unused-vars

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\components\modal\index.js
  32:15  warning  'e' is defined but never used  no-unused-vars

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\draw\draw.js
   132:8   warning  'e' is defined but never used                     no-unused-vars
   144:5   warning  Unexpected console statement                      no-console
   156:5   warning  Unexpected console statement                      no-console
   161:5   warning  Unexpected console statement                      no-console
   187:13  warning  Unexpected console statement                      no-console
   242:36  warning  'reject' is defined but never used                no-unused-vars
   265:9   warning  Unexpected console statement                      no-console
   329:5   warning  Unexpected console statement                      no-console
   358:5   warning  Unexpected console statement                      no-console
   367:12  warning  'e' is defined but never used                     no-unused-vars
   476:7   warning  'imgType' is assigned a value but never used      no-unused-vars
   506:20  warning  'add' is defined but never used                   no-unused-vars
   617:10  warning  'e' is defined but never used                     no-unused-vars
   844:22  warning  'res' is defined but never used                   no-unused-vars
   954:11  warning  'e' is defined but never used                     no-unused-vars
   959:9   warning  'res' is defined but never used                   no-unused-vars
  1226:22  warning  'e' is defined but never used                     no-unused-vars
  1228:7   warning  'layer' is assigned a value but never used        no-unused-vars
  1264:20  warning  'touch1' is assigned a value but never used       no-unused-vars
  1268:5   warning  Unexpected console statement                      no-console
  1276:16  warning  'touch1' is assigned a value but never used       no-unused-vars
  1293:16  warning  'touch1' is assigned a value but never used       no-unused-vars
  1306:5   warning  Unexpected console statement                      no-console
  1344:18  warning  'e' is defined but never used                     no-unused-vars
  1390:5   warning  Unexpected console statement                      no-console
  1540:13  warning  'doHistory' is assigned a value but never used    no-unused-vars
  1623:13  warning  'e' is defined but never used                     no-unused-vars
  1651:23  warning  'e' is defined but never used                     no-unused-vars
  1744:20  warning  'e' is defined but never used                     no-unused-vars
  1870:16  warning  'touch1' is assigned a value but never used       no-unused-vars
  1881:16  warning  'touch1' is assigned a value but never used       no-unused-vars
  1883:7   warning  'xMove' is assigned a value but never used        no-unused-vars
  1884:7   warning  'yMove' is assigned a value but never used        no-unused-vars
  1906:5   warning  Unexpected console statement                      no-console
  2124:13  warning  'e' is defined but never used                     no-unused-vars
  2517:11  warning  'that' is assigned a value but never used         no-unused-vars
  2518:7   warning  'type' is assigned a value but never used         no-unused-vars
  2521:8   warning  'e' is defined but never used                     no-unused-vars
  2552:11  warning  'e' is defined but never used                     no-unused-vars
  2561:7   warning  Unexpected console statement                      no-console
  2614:13  warning  Unexpected console statement                      no-console
  2618:11  warning  'id' is assigned a value but never used           no-unused-vars
  2628:11  warning  'width' is assigned a value but never used        no-unused-vars
  2629:11  warning  'height' is assigned a value but never used       no-unused-vars
  2632:11  warning  'layerHeight' is assigned a value but never used  no-unused-vars
  2633:11  warning  'layerWidth' is assigned a value but never used   no-unused-vars
  2651:39  warning  'arr' is defined but never used                   no-unused-vars
  2711:11  warning  Unexpected console statement                      no-console
  2717:19  warning  Unexpected console statement                      no-console
  2727:27  warning  'value' is defined but never used                 no-unused-vars
  2732:23  warning  Unexpected console statement                      no-console
  2866:10  warning  'getDistance' is defined but never used           no-unused-vars
  2877:10  warning  'countDeg' is defined but never used              no-unused-vars
  2913:10  warning  'createPreview' is defined but never used         no-unused-vars
  2987:10  warning  'gaussBlur' is defined but never used             no-unused-vars
  3135:10  warning  'initTextPreview' is defined but never used       no-unused-vars
  3143:7   warning  Unexpected console statement                      no-console
  3412:10  warning  'squarePoint' is defined but never used           no-unused-vars
  3450:10  warning  'isPointInMatrix' is defined but never used       no-unused-vars

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\index\index.js
  115:8   warning  'e' is defined but never used                      no-unused-vars
  126:5   warning  Unexpected console statement                       no-console
  137:21  warning  'options' is defined but never used                no-unused-vars
  155:7   warning  Unexpected console statement                       no-console
  220:32  warning  'e' is defined but never used                      no-unused-vars
  238:36  warning  'reject' is defined but never used                 no-unused-vars
  253:9   warning  'my_tagIndex' is assigned a value but never used   no-unused-vars
  254:9   warning  'my_tagList' is assigned a value but never used    no-unused-vars
  265:11  warning  Unexpected console statement                       no-console
  288:9   warning  Unexpected console statement                       no-console
  310:10  warning  'e' is defined but never used                      no-unused-vars
  315:9   warning  Unexpected console statement                       no-console
  336:9   warning  'home_tagList' is assigned a value but never used  no-unused-vars
  353:5   warning  Unexpected console statement                       no-console
  378:9   warning  'my_tagList' is assigned a value but never used    no-unused-vars
  380:5   warning  Unexpected console statement                       no-console
  403:17  warning  'e' is defined but never used                      no-unused-vars
  410:20  warning  'e' is defined but never used                      no-unused-vars
  425:19  warning  'e' is defined but never used                      no-unused-vars
  433:9   warning  Unexpected console statement                       no-console
  447:17  warning  'result' is defined but never used                 no-unused-vars
  457:15  warning  'e' is defined but never used                      no-unused-vars
  496:15  warning  'e' is defined but never used                      no-unused-vars
  507:15  warning  'e' is defined but never used                      no-unused-vars
  522:37  warning  'tl' is assigned a value but never used            no-unused-vars
  610:19  warning  'e' is defined but never used                      no-unused-vars
  618:7   warning  Unexpected console statement                       no-console
  636:11  warning  Unexpected console statement                       no-console
  639:45  warning  'reject' is defined but never used                 no-unused-vars
  653:23  warning  Unexpected console statement                       no-console
  659:19  warning  Unexpected console statement                       no-console
  665:35  warning  'res' is defined but never used                    no-unused-vars
  666:13  warning  Unexpected console statement                       no-console
  682:11  warning  Unexpected console statement                       no-console
  686:9   warning  Unexpected console statement                       no-console
  690:14  warning  'e' is defined but never used                      no-unused-vars
  705:16  warning  'e' is defined but never used                      no-unused-vars
  711:9   warning  'home_tagList' is assigned a value but never used  no-unused-vars
  715:5   warning  Unexpected console statement                       no-console

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\test\test.js
   9:25  warning  'e' is defined but never used  no-unused-vars
  17:21  warning  'e' is defined but never used  no-unused-vars

✖ 134 problems (24 errors, 110 warnings)


ERROR in C:/Users/12708/WeChatProjects/em-Copy/src/miniprogram/app.wxss (D:/node_global/node_modules/ewa-cli/node_modules/cache-loader/dist/cjs.js!D:/node_global/node_modules/ewa-cli/node_modules/css-loader/dist/cjs.js??ref--10-3!D:/node_global/node_modules/ewa-cli/node_modules/postcss-loader/dist/cjs.js??ref--10-4!D:/node_global/node_modules/ewa-cli/node_modules/resolve-url-loader!./loaders/fix-import-wxss-loader.js??ref--10-6!D:/node_global/node_modules/ewa-cli/node_modules/sass-loader/dist/cjs.js??ref--10-7!./loaders/import-wxss-loader.js??ref--10-8!C:/Users/12708/WeChatProjects/em-Copy/src/miniprogram/app.wxss)
Module build failed (from ./loaders/import-wxss-loader.js):
Error: Can't resolve '@/colorui/animation.wxss' in 'C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram'
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:209:21
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:657:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\AliasPlugin.js:67:43
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\RootPlugin.js:37:38
    at _next42 (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:27:15
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ C:/Users/12708/WeChatProjects/em-Copy/src/miniprogram/app.wxss 2:12-718 9:17-24 13:15-22

ERROR in C:/Users/12708/WeChatProjects/em-Copy/src/miniprogram/app.wxss
Module build failed (from D:/node_global/node_modules/ewa-cli/node_modules/cache-loader/dist/cjs.js):
ModuleBuildError: Module build failed (from ./loaders/import-wxss-loader.js):
Error: Can't resolve '@/colorui/main.wxss' in 'C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram'
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:209:21
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:657:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\AliasPlugin.js:67:43
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:44:7
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\RootPlugin.js:37:38
    at _next42 (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:67:43
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\Resolver.js:285:5
    at eval (eval at create (D:\node_global\node_modules\ewa-cli\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\DirectoryExistsPlugin.js:27:15
    at D:\node_global\node_modules\ewa-cli\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
    at D:\node_global\node_modules\ewa-cli\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\node_global\node_modules\ewa-cli\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\node_global\node_modules\ewa-cli\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\node_global\node_modules\ewa-cli\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\node_global\node_modules\ewa-cli\node_modules\ewa-webpack\lib\loaders\import-wxss-loader.js:53:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ C:/Users/12708/WeChatProjects/em-Copy/src/miniprogram/app.wxss

ERROR in
C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\app.js
  75:29  error  Empty block statement  no-empty

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\components\color-picker\color-picker.js
  249:13  error  Expected a conditional expression and instead saw an assignment  no-cond-assign
  252:20  error  Expected a conditional expression and instead saw an assignment  no-cond-assign

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\draw\draw.js
   477:9   error  Unexpected constant condition                    no-constant-condition
   498:12  error  Empty block statement                            no-empty
   669:9   error  Unexpected lexical declaration in case block     no-case-declarations
   669:9   error  Move function declaration to function body root  no-inner-declarations
   878:9   error  Unexpected lexical declaration in case block     no-case-declarations
   885:15  error  'layerWidth' is already defined                  no-redeclare
   886:13  error  'layerHeight' is already defined                 no-redeclare
   887:13  error  'x' is already defined                           no-redeclare
   888:13  error  'y' is already defined                           no-redeclare
   890:9   error  Unexpected lexical declaration in case block     no-case-declarations
   890:9   error  Move function declaration to function body root  no-inner-declarations
  1675:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1727:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1925:30  error  Empty block statement                            no-empty
  1944:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1958:9   error  Unexpected lexical declaration in case block     no-case-declarations
  2887:13  error  'angle' is assigned to itself                    no-self-assign
  3136:3   error  'that' is not defined                            no-undef
  3139:5   error  'that' is not defined                            no-undef
  3144:7   error  'that' is not defined                            no-undef

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\index\index.js
  275:12  error  Empty block statement  no-empty

✖ 130 problems (24 errors, 106 warnings)
```

**Comment by lyfeyaj** [comment]
你用的 ewa-cli 版本是什么？

**Comment by ltxhhz** [comment]
> 你用的 ewa-cli 版本是什么？

![image](https://user-images.githubusercontent.com/51697596/124448412-005f5980-ddb5-11eb-8e54-fdfdd5d8f038.png)

**Comment by lyfeyaj** [comment]
从上面的报错来看，样式是引用的路径有问题， wxss 里面的 @ 通常指向的是项目源代码根目录，也就是 src 文件夹

从你上面的截图来看，如 app.wxss：

```sass
// 目前的代码是👇
@import "@/colorui/main.wxss"
@import "@/colorui/icon.wxss"
@import "@/colorui/animation.wxss"
@import "@/icons/icon.wxss"

// 实际的路径应该是 👇
@import "@/miniprogram/colorui/main.wxss"
@import "@/miniprogram/colorui/icon.wxss"
@import "@/miniprogram/colorui/animation.wxss"
@import "@/miniprogram/icons/icon.wxss"
```

按照实际路径，修改成正确的应该就不会报错了

**Comment by ltxhhz** [comment]
> 从上面的报错来看，样式引用的路径有问题， wxss 里面的 @ 通常指向的是项目源代码根目录，也就是 src 文件夹
> 
> 从你上面的截图来看，如 app.wxss：
> 
> ```sass
> // 目前的代码中路径引用是👇
> @import "@/colorui/main.wxss"
> @import "@/colorui/icon.wxss"
> @import "@/colorui/animation.wxss"
> @import "@/icons/icon.wxss"
> 
> // 实际的路径应该是 👇
> @import "@/miniprogram/colorui/main.wxss"
> @import "@/miniprogram/colorui/icon.wxss"
> @import "@/miniprogram/colorui/animation.wxss"
> @import "@/miniprogram/icons/icon.wxss"
> ```
> 
> 按照实际路径修改成正确的引用，应该就不会报错了

本来那里是没有"@/"的，因为第一次就报错了，所以我就加上了，没想到没用，我再试试吧

**Comment by ltxhhz** [comment]
好的，wxss的问题是我路径的问题，剩下的报错我再改改代码吧

这些代码原本都没问题，害
```
ERROR in 
C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\draw\draw.js
   477:9   error  Unexpected constant condition                    no-constant-condition
   498:12  error  Empty block statement                            no-empty
   669:9   error  Unexpected lexical declaration in case block     no-case-declarations
   669:9   error  Move function declaration to function body root  no-inner-declarations
   878:9   error  Unexpected lexical declaration in case block     no-case-declarations
   885:15  error  'layerWidth' is already defined                  no-redeclare
   886:13  error  'layerHeight' is already defined                 no-redeclare
   887:13  error  'x' is already defined                           no-redeclare
   888:13  error  'y' is already defined                           no-redeclare
   890:9   error  Unexpected lexical declaration in case block     no-case-declarations
   890:9   error  Move function declaration to function body root  no-inner-declarations
  1675:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1727:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1925:30  error  Empty block statement                            no-empty
  1944:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1958:9   error  Unexpected lexical declaration in case block     no-case-declarations
  2887:13  error  'angle' is assigned to itself                    no-self-assign
  3136:3   error  'that' is not defined                            no-undef
  3139:5   error  'that' is not defined                            no-undef
  3144:7   error  'that' is not defined                            no-undef

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\index\index.js
  275:12  error  Empty block statement  no-empty

✖ 119 problems (21 errors, 98 warnings)
```

**Comment by lyfeyaj** [comment]
这些看上去都是 ESlint 的代码检查报错了，如果两个是第三方的库，你可以在这个两个顶部各加一行 `/* eslint-disable */` , 如果是不会第三方的，建议还是按照 ESlint 的报错，针对性的修改一下 ^_^


```
ERROR in 
C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\draw\draw.js
   477:9   error  Unexpected constant condition                    no-constant-condition
   498:12  error  Empty block statement                            no-empty
   669:9   error  Unexpected lexical declaration in case block     no-case-declarations
   669:9   error  Move function declaration to function body root  no-inner-declarations
   878:9   error  Unexpected lexical declaration in case block     no-case-declarations
   885:15  error  'layerWidth' is already defined                  no-redeclare
   886:13  error  'layerHeight' is already defined                 no-redeclare
   887:13  error  'x' is already defined                           no-redeclare
   888:13  error  'y' is already defined                           no-redeclare
   890:9   error  Unexpected lexical declaration in case block     no-case-declarations
   890:9   error  Move function declaration to function body root  no-inner-declarations
  1675:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1727:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1925:30  error  Empty block statement                            no-empty
  1944:9   error  Unexpected lexical declaration in case block     no-case-declarations
  1958:9   error  Unexpected lexical declaration in case block     no-case-declarations
  2887:13  error  'angle' is assigned to itself                    no-self-assign
  3136:3   error  'that' is not defined                            no-undef
  3139:5   error  'that' is not defined                            no-undef
  3144:7   error  'that' is not defined                            no-undef

C:\Users\12708\WeChatProjects\em-Copy\src\miniprogram\pages\index\index.js
  275:12  error  Empty block statement  no-empty

✖ 119 problems (21 errors, 98 warnings)
```

**Comment by ltxhhz** [comment]
好的，非常感谢哈
